image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Python Environment
    init: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install pandas numpy scikit-learn matplotlib jupyter seaborn
    command: |
      echo "Environment setup complete!"
      python app.py

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter

    